---
name: Submodule Updates
 
#############################
# Start the job on all push #
#############################
on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  COMMIT_MESSAGE: "chore: update submodules" 
 
###############
# Set the Job #
###############
jobs:
  build:
   name: Submodule update
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3
     with:  
          token: ${{ secrets.PAT }}  
          submodules: "true"  
   - name: Update submodule 
     run: |  
       git submodule update --init --recursive --remote
   - name: Commit changes  
     uses: stefanzweifel/git-auto-commit-action@v4  
     with:  
       commit_message: ${{ env.COMMIT_MESSAGE }}
